### PR TITLE
Status change automation

### PR DESCRIPTION
**Pull request by fredericpoitevin**
In addition to the default workflows controlled from https://github.com/orgs/lcls-users/projects/20/workflows, this workflow will change the status of an issue to "In Progress" when assigned.

### CODE REVIEW

**Review by gadorlhiac — CHANGES_REQUESTED** [review]
Thanks @fredericpoitevin - Seems reasonable, but there are some things we need to setup, most importantly an access token (`"#{{ secrets... }}"` line 17).

If I understand correctly, line 18 needs to be modified for the specific project, and any addtional projects will need to be added to the workflow action manually by modifying the YAML?

**Comment by fredericpoitevin** [comment]
Thanks for looking into this. My understanding is that the GITHUB_TOKEN is already setup but I'm not sure I 100% got it. Thanks for catching the project name missing. And yes I believe this will only work for the projects listed in the yaml.

I think I've fixed status.yml but we'll know that it works only after merging unfortunately (per https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues).

If we want to test, I've created the issue https://github.com/orgs/lcls-users/projects/20/views/2?pane=issue&itemId=66653257 which should be moved to "In Progress" once assigned to someone.

**Comment by gadorlhiac** [comment]
Hi @fredericpoitevin , I think the project looks correct, but I'm still not sure on where you are grabbing the secret from? I do not see any secrets in the repository or organization? I would expect there to be a secret named `GITHUB_TOKEN` under the repository secrets?

**Comment by fredericpoitevin** [comment]
I could be wrong but I think the `GITHUB_TOKEN` is [managed internally by GitHub Actions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret): 
> At the start of each workflow job, GitHub automatically creates a unique GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in the workflow job.

**Review by gadorlhiac — APPROVED** [review]
Ah okay, my bad - I'm used to providing secrets, I didn't know that this was autogenerated. Good to know!

I'll merge and we can test.

**Comment by fredericpoitevin** [comment]
Hmmm it does not seem to work as I thought: this action got triggered even though the issue was not part of the project... I'll remove this workflow unless we think it's really useful?

**Comment by gadorlhiac** [comment]
@fredericpoitevin  - It looks like maybe from this line onwards needs to be indented one level more: https://github.com/lcls-users/lcls-users/blob/32a4c7198fb051ffc4e89b1f10f160943b0ced3e/.github/workflows/status.yml#L14

Going off the marketplace template: https://github.com/marketplace/actions/move-issues-to-column

**Comment by fredericpoitevin** [comment]
I don't think that's it looking at that repo's own implementation: https://github.com/kin/gh-action-move-issues-to-column/blob/main/.github/workflows/baseline.yml

I'll just go ahead and remove the workflow for now. Thanks for looking into it!

**Comment by fredericpoitevin** [comment]
Removed: https://github.com/lcls-users/lcls-users/commit/92faa198e65495904738a607fa749caee308d4d0

**Pull request merged**
